---
- hosts: localhost
  remote_user: root
  vars:
    softs: 
      include: soft.yml
  tasks:
    - name: install basic packages
      apt:
        name:
          "{{ softs }}"
        state: present
        autoclean: yes
